config/routes.rb
ZombieApp::Application.routes.draw do
  get '/gears/new', controller: 'gears', action: 'new', :as => 'new_gear'
  post '/gears', controller: 'gears', action: 'create'

  get '/gears', controller: 'gears', action: 'index'
  get '/gears/:id', controller: 'gears', action: 'show', :as => 'gear'

  get '/gears/:id/edit', controller: 'gears', action: 'edit', :as => 'edit_gear'
  patch '/gears/:id', controller: 'gears', action: 'update'

  delete '/gears/:id', controller: 'gears', action: 'destroy'

end

app/models/gear.rb
class Gear < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gears_controller.rb
class GearsController < ApplicationController

  def index
    @gears = Gear.all

    if session[:viewed].present?
    @viewed_items = []
      session[:viewed].each do |id|
        @viewed_items << Gear.find(id)
     end
   end

  end

  def show
    @gear = Gear.find_by(:id => params[:id])
    if  session[:viewed] == nil
      session[:viewed] = []
    end

    session[:viewed] << params[:id]
    if session[:viewed].count > 5
      session[:viewed] = session[:viewed].last(5)
    end

  end

  def new
  end

  def create
    @gear = Gear.new
    @gear.name = params[:name]
    @gear.description = params[:description]
    @gear.price = params[:price]
    @gear.image_url = params[:image_url]

    if @gear.save
      redirect_to gears_url
    else
      render 'new'
    end
  end

  def edit
    @gear = Gear.find_by(:id => params[:id])
  end

  def update
    @gear = Gear.find_by(:id => params[:id])
    @gear.name = params[:name]
    @gear.description = params[:description]
    @gear.price = params[:price]
    @gear.image_url = params[:image_url]

    if @gear.save
      redirect_to gears_url
    else
      render 'new'
    end
  end

  def destroy
    @gear = Gear.find_by(:id => params[:id])
    @gear.destroy
    redirect_to gears_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gears_helper.rb
module GearsHelper
end

app/views/gears/edit.html.erb
<h1>Editing Gear #<%= @gear.id %></h1>


<%= form_tag(gear_url(@gear), method: 'patch') do %>

  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name, @gear.name %>
  </div>

  <div>
    <%= label_tag :description %><br />
    <%= text_area_tag :description, @gear.description %>
  </div>

  <div>
    <%= label_tag :price %><br />
    <%= number_field_tag :price, @gear.price %>
  </div>

  <div>
    <%= label_tag :image_url %><br />
    <%= text_field_tag :image_url, @gear.image_url %>
  </div>

  
  <div>
    <%= submit_tag "Update Gear" %>
  </div>

<% end %>

app/views/gears/index.html.erb
<h1>Zombie Apocalypse Survival Gear</h1>
<div class='image'>
<% if @viewed_items.present? %>
  <% @viewed_items.each do |view| %>
  <%= image_tag view.image_url %>
  <% end %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Image URL</th>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
    </tr>
  </thead>

  <tbody>
  <% @gears.each do |gear| %>
    <tr>
      <td><%= image_tag gear.image_url %></td>
      <td><%= link_to gear.name, gear_url(gear) %></td>
      <td><%= gear.description %></td>
      <td><%= number_to_currency(gear.price) %></td>

    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/gears/new.html.erb
<h1>New Gear</h1>


<%= form_tag(gears_url, method: 'post') do %>


  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name %>
  </div>

  <div>
    <%= label_tag :description %><br />
    <%= text_area_tag :description %>
  </div>

  <div>
    <%= label_tag :price %><br />
    <%= number_field_tag :price %>
  </div>

  <div>
    <%= label_tag :image_url %><br />
    <%= text_field_tag :image_url %>
  </div>


  <div>
    <%= submit_tag "Create Gear" %>
  </div>
<% end %>

app/views/gears/show.html.erb
<h1 class = 'big_image'><%= image_tag @gear.image_url %></h1>

<p>
  <b>Name:</b>
  <%= @gear.name %>
</p>

<p>
  <b>Description:</b>
  <%= @gear.description %>
</p>

<p>
  <b>Price:</b>
  <%= number_to_currency(@gear.price) %>
</p>

<p>
<%= link_to "Return to master list", gears_url %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ZombieApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>